name: Deploy FE
on:
  push:
    branches:
      - main

jobs:
  build_and_push_to_container_registry:
    name: Build And Push to Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.19.0
      - run: |
          npm install yarn -g
          # rm package-lock.json
          yarn install --frozen-lockfile
          yarn run build
      - name: Remove image
        run: docker rmi --force 'cs5421_web_react_client'
      - name: Build image
        run: docker build -t cs5421_web_react_client .
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 600
      - name: Tag image
        run:
          docker tag cs5421_web_react_client registry.digitalocean.com/coconut/cs5421_web_react_client:latest
          # registry.digitalocean.com/coconut/cs5421_web_react_client:${{github.event.inputs.version}}

      - name: Push image to DO Container Registry
        run: docker push registry.digitalocean.com/coconut/cs5421_web_react_client:latest

  deploy_to_digital_ocean_dropplet:
    name: Deploy to Digital Ocean Droplet
    runs-on: ubuntu-latest
    needs: build_and_push_to_container_registry

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            # Stop all running Docker Containers
            if [ -z "$(docker ps -q)" ]; then
              echo "No running containers found."
            else
            docker kill $(docker ps -q)
            fi

            # Free up space
            docker system prune -a

            # Login to Github Container Registry
            # docker login registry.digitalocean.com
            doctl registry login

            # Pull the Docker Image 
            docker pull registry.digitalocean.com/coconut/cs5421_web_react_client:latest

            # Run a new container from a new image
            docker run -d --network host -t registry.digitalocean.com/coconut/cs5421_web_react_client:latest
